# UNIT CIRCLE / TRIGINOMETRY
### 1. **Table of the Unit Circle Values**
The unit circle typically includes key angles (in degrees and radians) along with their corresponding sine and cosine values. We’ll create a table of these values.

### 2. **Memorization Lists**
We’ll list the angles and their sine and cosine values separately to help with memorization.

### 3. **Flashcard Game**
We’ll create a flashcard game where users are prompted to guess either the sine, cosine, or angle given the other value, and check their answer.

---

### Step 1: **Create the Unit Circle Table**

Let’s first create the core data structure for the unit circle. We’ll use a dictionary or list of tuples to store key angles (both degrees and radians) and their corresponding sine and cosine values.


In [3]:
import math
from IPython.display import display, Math

# Unit circle key points (angle in degrees, angle in radians, (cos, sin))
unit_circle = [
    (0, 0, (1, 0)),
    (30, math.radians(30), (math.sqrt(3)/2, 1/2)),
    (45, math.radians(45), (math.sqrt(2)/2, math.sqrt(2)/2)),
    (60, math.radians(60), (1/2, math.sqrt(3)/2)),
    (90, math.radians(90), (0, 1)),
    # Add 120 - 180 degrees
    (120, math.radians(120), (-1/2, math.sqrt(3)/2)),
    (135, math.radians(135), (-math.sqrt(2)/2, math.sqrt(2)/2)),
    (150, math.radians(150), (-math.sqrt(3)/2, 1/2)),
    (180, math.radians(180), (-1, 0)),
    # Add 210 - 270 degrees
    (210, math.radians(210), (-math.sqrt(3)/2, -1/2)),
    (225, math.radians(225), (-math.sqrt(2)/2, -math.sqrt(2)/2)),
    (240, math.radians(240), (-1/2, -math.sqrt(3)/2)),
    (270, math.radians(270), (0, -1)),
    # Add 300 - 360 degrees
    (300, math.radians(300), (1/2, -math.sqrt(3)/2)),
    (315, math.radians(315), (math.sqrt(2)/2, -math.sqrt(2)/2)),
    (330, math.radians(330), (math.sqrt(3)/2, -1/2)),
    (360, math.radians(360), (1, 0))
]

def format_value(value):
    """
    Format the value for LaTeX display.
    """
    if value == 0:
        return "0"
    elif value == 1:
        return "1"
    elif value == -1:
        return "-1"
    elif value == 1/2:
        return r"\frac{1}{2}"
    elif value == -1/2:
        return r"-\frac{1}{2}"
    elif value == math.sqrt(2)/2:
        return r"\frac{\sqrt{2}}{2}"
    elif value == -math.sqrt(2)/2:
        return r"-\frac{\sqrt{2}}{2}"
    elif value == math.sqrt(3)/2:
        return r"\frac{\sqrt{3}}{2}"
    elif value == -math.sqrt(3)/2:
        return r"-\frac{\sqrt{3}}{2}"
    elif value == math.sqrt(3):
        return r"\sqrt{3}"
    elif value == -math.sqrt(3):
        return r"-\sqrt{3}"
    elif value == 2:
        return "2"
    elif value == -2:
      return "-2"
    elif value == math.sqrt(3)/3:
        return r"\frac{\sqrt{3}}{3}"
    elif value == -math.sqrt(3)/3:
        return r"-\frac{\sqrt{3}}{3}"
    elif value == 2*math.sqrt(3)/3:
        return r"\frac{2\sqrt{3}}{3}"
    elif value == -2*math.sqrt(3)/3:
        return r"-\frac{2\sqrt{3}}{3}"
    else:
        return f"{value:.5f}"

def display_unit_circle():
    """
    Display the unit circle table with degrees, radians, cos, and sin values.
    """
    print(f"{'Degrees':<10} {'Radians':<15} {'cos(θ)':<10} {'sin(θ)':<10}")
    print("-" * 40)
    for degrees, radians, (cos_val, sin_val) in unit_circle:
        print(f"{degrees:<10} {radians:<15.5f} {cos_val:<10.5f} {sin_val:<10.5f}")

# Call the function to display the table
display_unit_circle()

Degrees    Radians         cos(θ)     sin(θ)    
----------------------------------------
0          0.00000         1.00000    0.00000   
30         0.52360         0.86603    0.50000   
45         0.78540         0.70711    0.70711   
60         1.04720         0.50000    0.86603   
90         1.57080         0.00000    1.00000   
120        2.09440         -0.50000   0.86603   
135        2.35619         -0.70711   0.70711   
150        2.61799         -0.86603   0.50000   
180        3.14159         -1.00000   0.00000   
210        3.66519         -0.86603   -0.50000  
225        3.92699         -0.70711   -0.70711  
240        4.18879         -0.50000   -0.86603  
270        4.71239         0.00000    -1.00000  
300        5.23599         0.50000    -0.86603  
315        5.49779         0.70711    -0.70711  
330        5.75959         0.86603    -0.50000  
360        6.28319         1.00000    0.00000   


In [5]:
def display_unit_circle_latex():
    """
    Display the unit circle table with degrees, radians, cos, sin, tan, cot, sec, and csc values in LaTeX.
    """
    latex_str = r"\begin{array}{|c|c|c|c|c|c|c|c|}\hline"
    latex_str += r"\text{Degrees} & \text{Radians} & \cos(\theta) & \sin(\theta) & \tan(\theta) & \cot(\theta) & \sec(\theta) & \csc(\theta) \\ \hline"
    for degrees, radians, (cos_val, sin_val) in unit_circle:
        tan_val = sin_val / cos_val if cos_val != 0 else float('inf')
        cot_val = cos_val / sin_val if sin_val != 0 else float('inf')
        sec_val = 1 / cos_val if cos_val != 0 else float('inf')
        csc_val = 1 / sin_val if sin_val != 0 else float('inf')
        
        cos_latex = format_value(cos_val)
        sin_latex = format_value(sin_val)
        tan_latex = format_value(tan_val)
        cot_latex = format_value(cot_val)
        sec_latex = format_value(sec_val)
        csc_latex = format_value(csc_val)
        
        latex_str += f"{degrees} & {radians:.5f} & {cos_latex} & {sin_latex} & {tan_latex} & {cot_latex} & {sec_latex} & {csc_latex} \\\\ \hline"
    latex_str += r"\end{array}"
    display(Math(latex_str))

# Call the function to display the table
display_unit_circle_latex()

<IPython.core.display.Math object>

### Step 2: **Create Memorization Lists**
We can create separate lists to memorize the key angles and their corresponding sine and cosine values.

In [6]:
def memorization_lists():
    """
    Display angles with corresponding sine and cosine values for memorization.
    """
    print("Memorize these key angles and their corresponding values:")
    for degrees, radians, (cos_val, sin_val) in unit_circle:
        print(f"Angle: {degrees}° | cos(θ) = {cos_val:.3f}, sin(θ) = {sin_val:.3f}")

# Call the function to display the memorization list
memorization_lists()

Memorize these key angles and their corresponding values:
Angle: 0° | cos(θ) = 1.000, sin(θ) = 0.000
Angle: 30° | cos(θ) = 0.866, sin(θ) = 0.500
Angle: 45° | cos(θ) = 0.707, sin(θ) = 0.707
Angle: 60° | cos(θ) = 0.500, sin(θ) = 0.866
Angle: 90° | cos(θ) = 0.000, sin(θ) = 1.000
Angle: 120° | cos(θ) = -0.500, sin(θ) = 0.866
Angle: 135° | cos(θ) = -0.707, sin(θ) = 0.707
Angle: 150° | cos(θ) = -0.866, sin(θ) = 0.500
Angle: 180° | cos(θ) = -1.000, sin(θ) = 0.000
Angle: 210° | cos(θ) = -0.866, sin(θ) = -0.500
Angle: 225° | cos(θ) = -0.707, sin(θ) = -0.707
Angle: 240° | cos(θ) = -0.500, sin(θ) = -0.866
Angle: 270° | cos(θ) = 0.000, sin(θ) = -1.000
Angle: 300° | cos(θ) = 0.500, sin(θ) = -0.866
Angle: 315° | cos(θ) = 0.707, sin(θ) = -0.707
Angle: 330° | cos(θ) = 0.866, sin(θ) = -0.500
Angle: 360° | cos(θ) = 1.000, sin(θ) = 0.000


### Step 3: **Flashcard Game**
Now, we can create a flashcard game where the user is prompted with either an angle or a trigonometric value and asked to guess the corresponding value.

In [ ]:
import random

def flashcard_game():
    """
    Flashcard game to guess sine or cosine values for unit circle angles.
    """
    score = 0
    num_questions = 5  # Number of questions in the game
    
    for _ in range(num_questions):
        # Randomly select an angle from the unit circle
        degrees, radians, (cos_val, sin_val) = random.choice(unit_circle)
        
        # Randomly ask for either sine or cosine
        quiz_type = random.choice(['cos', 'sin'])
        
        if quiz_type == 'cos':
            answer = float(input(f"What is cos({degrees}°)? "))
            if math.isclose(answer, cos_val, rel_tol=1e-2):
                print("Correct!")
                score += 1
            else:
                print(f"Incorrect. The correct value is {cos_val:.3f}.")
        elif quiz_type == 'sin':
            answer = float(input(f"What is sin({degrees}°)? "))
            if math.isclose(answer, sin_val, rel_tol=1e-2):
                print("Correct!")
                score += 1
            else:
                print(f"Incorrect. The correct value is {sin_val:.3f}.")
    
    print(f"Game over! Your score: {score}/{num_questions}")

# Run the flashcard game
flashcard_game()


### Flashcard Game Flow:
1. **Question Generation**: The program randomly selects a key angle from the unit circle.
2. **Answer Prompt**: It prompts the user to guess the corresponding sine or cosine value.
3. **Feedback**: The program checks the answer and provides immediate feedback, tracking the score.

---

### Next Steps:
- **Expansion of Unit Circle Values**: You can add more angles (like 120°, 135°, etc.) to the `unit_circle` list.
- **Visual Representation**: If you want, we can later add a visual tool to display the unit circle graphically.
- **More Question Types**: You could ask the user to guess the angle given the sine or cosine value.